name: sync-spotify-plays
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        run: |
          ./src/jobs/sync-spotify-plays.sh ${{ secrets.ORIGIN }} ${{ secrets.API_SECRET_KEY }}
